Hw2 hw3
Lina-Karyzhska/Js_module pull request #3
Opened 2020-12-04 19:31 UTC by Lina-Karyzhska

2020-12-05 13:20 UTC, idovbush commented on 2hw/main.js
> +        resalt *= K_EUR;
result*

2020-12-05 13:21 UTC, idovbush commented on 2hw/main.js
> +  if (sum < 300 && sum >= 200) {
here you should have to count sum with discount and write it

2020-12-05 17:29 UTC, Lina-Karyzhska commented on 2hw/main.js
> +  if (sum < 300 && sum >= 200) {
Oops)

2020-12-06 16:49 UTC, idovbush commented on 3hw/main.js
> +first_number % 1 == 0 ? first_addend = first_number : first_addend = first_number + (1 - first_number % 1);
this is not readable at all you should rewrite it like first_addend = first_number % 1 == 0 ? first_number : first_number + (1 - first_number % 1);

2020-12-06 17:45 UTC, idovbush commented on 3hw/main.js
> +} while (bul == "yes")
here but I believe it should have been bool but in any case it is wrong mane for variable because it is not boolean at all, it's string

2020-12-06 17:46 UTC, idovbush commented on 3hw/main.js
> +    if (!number1 || !number2 || (action != "+" && action != "-" && action != "*" && action != "/" && action != "^")) {
(action != "+" && action != "-" && action != "*" && action != "/" && action != "^") this all cases can be handled in default  statement

2020-12-06 17:48 UTC, idovbush requested changes
this code can be improved

2020-12-09 11:35 UTC, merged

2020-12-09 13:04 UTC, idovbush commented on 2hw/main.js
> +    console.log("this isn't a five-digit number.")
this is very good that you check all possible cases